services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: faithtech_user
      POSTGRES_PASSWORD: faithtech_password
      POSTGRES_DB: faithtech_create
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 

  nestjs:
    build:
      context: ./server
    container_name: nestjs
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: faithtech_user
      DATABASE_PASSWORD: faithtech_password
      DATABASE_NAME: faithtech_create
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  react:
    build:
      context: ./client
    container_name: react
    ports:
      - "8081:3000"
    expose:
      - 8081
    depends_on:
      - nestjs

volumes:
  postgres_data: